# Configura\u00c3\u00a7\u00c3\u00a3o de banco de dados do MyContacts
# Use MySQL por padr\u00c3\u00a3o.
# Para usar SQLite, comente as propriedades do MySQL e descomente a URL abaixo.

#db.url=jdbc:sqlite:mycontacts.db
db.url=jdbc:mysql://localhost:3306/mycontacts
db.user=root
db.password=14122509
